namespace MELCloudApiClient.Enums;
public enum Language
{
    English = 0,
    Bulgarian = 1,
    Czech = 2,
    Danish = 3,
    German = 4,
    Estonian = 5,
    Spanish = 6,
    French = 7,
    Armenian = 8,
    Latvian = 9,
    Lithuanian = 10,
    Hungarian = 11,
    Dutch = 12,
    Norwegian = 13,
    Polish = 14,
    Portuguese = 15,
    Russian = 16,
    Finnish = 17,
    Swedish = 18,
    Italian = 19,
    Ukrainian = 20,
    Turkish = 21,
    Greek = 22,
    CroatianSerbian = 23,
    Romanian = 24,
    Slovenian = 25,
    Albanian = 26
}